im facing issue while run with selenium-server-standalone-3.0.0-beta3
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
,"syncGUID":"zARNe_oFmFcA","location":"app-global","version":"48.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1473062810473,"updateDate":1473062810473,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"48.0.2","maxVersion":"48.0.2"}],"targetPlatforms":[],"seen":true}
1473923654823	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1473923654824	DeferredSave.extensions.json	DEBUG	Save changes
1473923654824	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1473923654825	addons.xpi-utils	DEBUG	Updating add-on states
1473923654825	addons.xpi-utils	DEBUG	Writing add-ons list
1473923654827	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1473923654828	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
1473923654828	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1473923654828	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1473923654829	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1473923654830	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
1473923654850	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1473923654850	addons.manager	DEBUG	Provider finished startup: XPIProvider
1473923654850	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1473923654850	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1473923654850	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1473923654851	addons.manager	DEBUG	Starting provider: GMPProvider
1473923654857	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1473923654857	addons.manager	DEBUG	Provider finished startup: GMPProvider
1473923654857	addons.manager	DEBUG	Starting provider: PluginProvider
1473923654857	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1473923654857	addons.manager	DEBUG	Provider finished startup: PluginProvider
1473923654858	addons.manager	DEBUG	Completed startup sequence
1473923656335	DeferredSave.extensions.json	DEBUG	Starting write
1473923656341	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1473923656341	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1473923656341	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1473923656612	addons.repository	DEBUG	No addons.json found.
1473923656612	DeferredSave.addons.json	DEBUG	Save changes
1473923656615	DeferredSave.addons.json	DEBUG	Starting timer
1473923656640	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1473923656640	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1473923656640	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1473923656642	DeferredSave.extensions.json	DEBUG	Write succeeded
1473923656642	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1473923656668	DeferredSave.addons.json	DEBUG	Starting write
1473923656727	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)